### ISSUE TITLE
question on stream writer performance

### ISSUE THREAD

**Issue by aawise** [indygreg/python-zstandard#62] opened 2018-11-06 03:36 UTC
I've been testing out ways of compressing json objects, and surprisingly (at least to me), connecting the streams is much slower than simply dumping an entire object:

In my example code, this takes 0.8s on pypy3, 0.9s on python3
```
with open(output_path, 'wb') as f:
    cctx = zstd.ZstdCompressor()
    with cctx.stream_writer(f) as compressor:
        compressor.write(json.dumps(my_map).encode())
```

And this takes 54s on pypy3, 6s on python3
```
with open(output_path, 'wb') as f:
    cctx = zstd.ZstdCompressor()
    with cctx.stream_writer(f) as compressor:
        compressor2 = codecs.getwriter('utf-8')(compressor)
        json.dump(my_map, compressor2)
```

Is this expected?  Alternatively, is there a better way for streaming to the compressor without putting the whole object in memory?

**Comment by indygreg** [comment] 2018-11-06 04:04
That performance is definitely... odd.

I'd love to see a profile (preferably a flame graph) showing where the time is spent in the slow case. I recommend https://github.com/benfred/py-spy for creating one.

There's a chance all the "slow" code will be in C and that profiling won't make things obvious. But let's get a profile and see what it says first.

I have a hunch that the overhead is due to tens of thousands of `write()` calls. Python function call overhead is real. And if we're invoking the zstd compressor on e.g. 1 byte inputs, that could contribute significant overhead as well.

Looking at the code, it looks like we allocate a buffer to hold the compressed output for every call to `write()`. If we used a shared buffer across calls, that would almost certainly make things faster.

Also, if you could give me a JSON file to use to reproduce the slowness, it would help a lot. Even just telling me something like "it is an array with N entries where each entry is a string averaging X characters long" would probably be enough.

**Comment by aawise** [comment] 2018-11-06 05:11
Here's a minimal example and the output of py-spy on it (for python 3.6 on my mac; I couldn't trivially get py-spy working on pypy).  Runtimes are ~0.9s for a.zst, and 6.4s for b.zst.

```
import random
import string
import codecs
import json
import time
import zstd


my_map = {}

for i in range(500000):
    my_map[''.join(random.choices(string.ascii_lowercase, k=7))] = random.uniform(0,1)

#start = time.time()
with open('a.zst', 'wb') as f:
    cctx = zstd.ZstdCompressor()
    with cctx.stream_writer(f) as compressor:
        j_dump = json.dumps(my_map)
        j_enc = j_dump.encode()
        compressor.write(j_enc)
#print(time.time()-start)

#start = time.time()
with open('b.zst', 'wb') as f:
    cctx = zstd.ZstdCompressor()
    with cctx.stream_writer(f) as compressor:
        compressor2 = codecs.getwriter('utf-8')(compressor)
        json.dump(my_map, compressor2)
#print(time.time()-start)

```
[profile.svg.zip](https://github.com/indygreg/python-zstandard/files/2551630/profile.svg.zip)



Thanks for the help!

**Comment by aawise** [comment] 2018-11-06 05:31
The trace made me curious about the codec performance.  Here's a similar example using gzip.  a.gz takes 3.5s, b.gz takes 4.5s, c.gz takes 10.81.  Looks like the codec is not well suited to this sort of use case.  And I'm still surprised that a.gz is faster than b.gz

```
start = time.time()
with gzip.open('a.gz', 'wb') as f:
    j_dump = json.dumps(my_map)
    j_enc = j_dump.encode()
    f.write(j_enc)
print(time.time()-start)

start = time.time()
with gzip.open('b.gz', 'wt') as f:
    json.dump(my_map, f)
print(time.time()-start)

start = time.time()
with gzip.open('c.gz', 'wb') as f:
    compressor2 = codecs.getwriter('utf-8')(f)
    json.dump(my_map, compressor2)
print(time.time()-start)
```

**Comment by indygreg** [comment] 2018-11-06 17:32
So, codec looks to be responsible for several seconds.

And I'm not surprised a is faster than b. Assuming the JSON data fits in memory, it will be faster to allocate fewer large buffers and perform fewer operations in aggregate than to perform a lot of small operations (which is what `json.dump()` is doing).

I reckon I can make python-zstandard much faster by reusing an internal buffer. But there's still the overhead of calling `write()` into zstandard many times. You could potentially offset that by using an `io.BufferedWriter` before compression.

You may also want to look at alternate JSON encoders. If one supports internally buffering data so it doesn't call into `write()` so many times, it will likely be much faster. Or if there's a JSON encoder that supports emitting a generator of *chunks*, that should perform better as well.

**Comment by indygreg** [comment] 2018-11-06 17:42
Looking at the profile, try making an `io.BufferedWriter` to receive the writes for `json.dump()`. Then have that `write()` into a `codecs.getwriter()`, which writes into the zstd compressor, which writes into a file.

**Comment by aawise** [comment] 2018-11-06 18:15
So adding a bufferedwriter, the code snippet looks like this:
```
with open('c.zst', 'wb') as f:
    cctx = zstd.ZstdCompressor()
    with cctx.stream_writer(f) as compressor:
        compressor2 = codecs.getwriter('utf-8')(compressor)
        o_buf = io.BufferedWriter(compressor2)
        json.dump(my_map, o_buf)
```

which gives an error
```
Traceback (most recent call last):
  File "test_zstd.py", line 38, in <module>
    i_buf = io.BufferedWriter(compressor2)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 408, in __getattr__
    return getattr(self.stream, name)
AttributeError: 'zstd.ZstdCompressionWriter' object has no attribute 'writable'
```

**Comment by indygreg** [comment] 2018-11-06 21:55
That error is due to `stream_writer()` not implementing the `io.IOBase` interface. That can (and probably should) be changed.

There may be an open issue on it though. The topic of implementing those interfaces has come up in other issues.

The `stream_reader()` API does implement the necessary interface. But since `json.dump()` is `write()`ing to a file object, you can't easily produce a file object that you can `read()` data from.

This is the problem with APIs that perform I/O. I'm a big fan of "sans I/O" APIs that e.g. expose a generator of chunks and allow the consumer to hook that up to file objects as appropriate. Having that as your fundamental primitive allows so much more flexibility. But here we are and there's not much we can do about `json` APIs in the standard library.

**Comment by indygreg** [comment] 2019-02-17 03:22
As of a few minutes ago, the master branch implements the entirety of the ``io.RawIOBase`` interface for ``ZstdCompressor.stream_writer()``. This means that hooking up a compressing stream to e.g. a ``codecs.StreamWriter()`` "just works."

Using code based on your examples:

```
import gzip
import io
import random
import string
import codecs
import json
import time
import zstd


my_map = {}

for i in range(500000):
    my_map[''.join(random.choices(string.ascii_lowercase, k=7))] = random.uniform(0,1)

start = time.time()
with open('a.zst', 'wb') as f:
    cctx = zstd.ZstdCompressor()
    with cctx.stream_writer(f, write_return_read=True) as compressor:
        b = io.BufferedWriter(compressor)
        encoder = codecs.getwriter('utf-8')(b)
        json.dump(my_map, encoder)
        encoder.close()

print(time.time() - start)

start = time.time()
with open('a.zst', 'wb') as f:
    cctx = zstd.ZstdCompressor()

    with cctx.stream_writer(f, write_return_read=True) as compressor:
        encoder = codecs.getwriter('utf-8')(compressor)
        json.dump(my_map, encoder)
        encoder.close()

print(time.time() - start)

start = time.time()
with gzip.open('a.gz', 'wt') as f:
    json.dump(my_map, f)
print(time.time()-start)
```

This prints:

```
1.8561596870422363
1.9854204654693604
3.326624870300293
```

So, python-zstandard is now faster than gzip across the board. Using an ``io.BufferedWriter()`` to cut down on the number of calls into compression helps a little. But not much.

Since performance is no longer an issue, I'm going to call this one closed.

**Closed by indygreg** 2019-02-17 03:22 UTC
