### ISSUE TITLE
Segmentation fault after catching exception

### ISSUE THREAD

**Issue by gwk** [indygreg/python-zstandard#56] opened 2018-10-08 12:25 UTC
I encountered a segmentation fault after misusing the API in the interactive REPL. Below is a reproduction. This was found on macOS 10.14; the file `empty.txt.zst` was created by compressing an empty file using the `zstd` command line utility obtained via Homebrew. I suspect that this is a problem with the python bindings though, and probably not dependent on platform or archive contents. Happy to provide more info as necessary.

```
from zstandard import ZstdDecompressor
f = open('empty.txt.zst', 'rb')
decompressor = ZstdDecompressor()
df = decompressor.stream_reader(f)

try:
  with df:
    df.read() # TypeError: function missing required argument 'size' (pos 1).
except Exception as e:
  print(type(e), e)

with df:
  df.read(100) # Segmentation fault.

```

**Comment by indygreg** [comment] 2018-10-08 16:54
Thanks for the report and the reproduce case!

I can reproduce the segfault on Linux against 0.9.1.

The good news is when I added the test to master, it passed. This is probably due to some refactoring of `stream_reader()` in the latest code. So a fix for this will be in 0.10.0, which I'm hoping to release in the next few hours.

**Closed by indygreg** 2018-10-08 16:54 UTC
