### ISSUE TITLE
Build system used is complete mess

### ISSUE THREAD

**Issue by KOLANICH** [indygreg/python-zstandard#89] opened 2019-08-20 11:21 UTC
1. to add some compiler flags I had to visit 3 different places
2. it uses hardcoded paths to `.c` files. It had broken upgrade to the latest zstd version. I had to add a couple of files there. Into 2 different places.
3. it uses `distutils.ccompiler.new_compiler` which uses `get_default_compiler` which uses a dict, into which `msvc` is hardcoded for Windows. I use MinGW-w64. It is gcc which generates faster code and also a free software without espionage features seen in MSVC.
4. to add support of mingw-w64 I had to edit some files.
5. it is an untidy mess of python code, compiler flags and strings containing pieces of C code.
6. it doesn't fetch the latest zstd sources automatically but uses the ones in the repo
7. building is damn slow. in order to do a small change everything has to be rebuilt.

So I suggest to use CMake + Ninja or Meson.

**Comment by indygreg** [comment] 2019-09-14 03:33
Sadly the methods I use are pretty typical for a Python C extension. Python's packaging/build tools just aren't that great. I've also written some Python code on top of the usual `setup.py` ugliness to make it easier to integrate python-zstandard's build into other Python projects (like Mercurial). And most of the ugly code is to support cffi, which needs to parse C headers to extract function definitions. I concede that is ugly.

The vendoring of the zstd sources is intentional: python-zstandard uses internal APIs and behavior is very specific to the zstd library version. The README goes into more detail. I also prefer builds to be deterministic and reproducible. Fetching the latest sources would not yield those properties.

I'm pretty sure there is a way to trick `setup.py` into using MingGW on Windows.

Since the build system is inline with what pretty much every other Python C extension uses, I'm going to close this issue. If you have specific suggestions for improvements that involve following better Python packaging practices, I'm receptive to new ideas.

**Closed by indygreg** 2019-09-14 03:33 UTC
